// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Remove type import for now to avoid runtime issues
// import type { Database } from './types';

const SUPABASE_URL = "https://pamxkxrabrhrjtofywsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbXhreHJhYnJocmp0b2Z5d3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjcwNTMsImV4cCI6MjA2NzEwMzA1M30.MiiLeojcIn7LF8PvwUufycmGhzc2GBq3avKa3kW7-vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);